services:
  - docker

before_script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build/RPMS

script:
  - docker run -v ${TRAVIS_BUILD_DIR}/build:/build ubuntu /bin/sh -c "touch /build/RPMS/test-build.rpm"
  - ls -la ${TRAVIS_BUILD_DIR}/build/RPMS
  - echo ${TRAVIS_BUILD_DIR}
  - pwd

deploy:
  provider: bintray
  file: ".bintray.json"
  user: functor
  key: "KEY"
  dry-run: true
